optimizer :
  type: AdamW
  kwargs:
    lr: 0.001
    weight_decay: 0.05


scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs : 10


dataset:
  train:
    _base_: cfgs/dataset_configs/ShapeNet-55.yaml
    others: 
      subset: train
      npoints: 1024
      whole: True
  val:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others: 
      subset: test
  extra_train:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others: 
      subset: train


model:
  NAME: Point-RAE
  loss: cosine
  reg_depth: 4
  reg_num_head: 6

  transformer_config:
    mask_ratio: 0.8
    mask_type: 'rand'
    proj: linear
    embed_dim: 384
    encoder_dims: 384
    depth: 12
    drop_path_rate: 0.1
    cls_dim: 512
    replace_pob: 0.
    num_heads: 6
    decoder_depth: 2
    decoder_num_heads: 6
    return_all_tokens: False
    cls_loss: False
    register_shallow_hook: 9

  dvae_config:
    # ViT
    visual_embed_type: vit_base_patch16_384
    visual_embed_dim: 768
    visual_embed_pos: after_dgcnn1
    freeze_visual_embed: true
    num_prompt_token: 64
    # num_prompt_token: 132 # MLP-Mixer
    use_deep_prompt: true
    num_group: 64
    group_size: 32
    encoder_dims: 384
    num_tokens: 8192
    tokens_dims: 384
    decoder_dims: 384
    ckpt: 'model_zoo/ckpt_act_dvae.pth' # set the dVAE weight here

total_bs: 128
step_per_update: 1
max_epoch: 300

consider_metric: CDL1
